#!/bin/bash
clear
IPC=$(ip route get 9.9.9.9 | grep -oP 'src \K\S+')
read -p "Enter IP of replication partner: " ipaddy
echo
service ssh stop > /dev/null ; sed -i 's*PasswordAuthentication no*PasswordAuthentication yes*g' /etc/ssh/sshd_config ; service ssh start > /dev/null
pass=$(xkcdpass -n 4 -d - ) ; echo gs4wsl1:$pass | sudo chpasswd > /dev/null 2>&1
echo REMOTE_HOST=\'$ipaddy\' >  /etc/gravity-sync/gravity-sync.conf ; echo REMOTE_USER=\'root\' >> /etc/gravity-sync/gravity-sync.conf
echo ------------------------------------------------------- ;echo Run this command on replication partner: ; echo ------------------------------------------------------- ; echo
echo "echo cname=\$HOSTNAME.local,\$HOSTNAME > /etc/dnsmasq.d/05-pihole-custom-cname.conf ; mkdir -p /etc/gravity-sync/.gs/templates ; echo REMOTE_HOST=\'$IPC\' >  /etc/gravity-sync/gravity-sync.conf ; echo REMOTE_USER=\'gs4wsl1\' >> /etc/gravity-sync/gravity-sync.conf ; echo GS_SSH_PORT=\'5322\' >> /etc/gravity-sync/gravity-sync.conf ; wget -q https://github.com/vmstan/gravity-sync/archive/refs/heads/4.0.0.zip -O gs.zip ; unzip -o -q gs.zip ; cp ./gravity-sync-4.0.0/templates/* /etc/gravity-sync/.gs/templates/ ; cp ./gravity-sync-4.0.0/gravity-sync /usr/local/bin/ ; if ! [ -f ~/.ssh/id_rsa ] ; then ssh-keygen -t ed25519 -N '' -f ~/.ssh/id_rsa ; fi ; cp ~/.ssh/id_rsa /etc/gravity-sync/gravity-sync.rsa ; cp ~/.ssh/id_rsa.pub /etc/gravity-sync/gravity-sync.rsa.pub ; SSHPASS='$pass' sshpass -e ssh-copy-id -f -p 5322 -o StrictHostKeyChecking=no gs4wsl1@$IPC > /dev/null 2>&1; echo ; /usr/local/bin/gravity-sync auto ; /usr/local/bin/gravity-sync info"
echo ; read -p "IMPORTANT: Leave this window open unitl replication partner setup is complete.  Then, hit [Ehter] to close this window."
service ssh stop > /dev/null ; sed -i 's*PasswordAuthentication yes*PasswordAuthentication no*g' /etc/ssh/sshd_config ; service ssh start > /dev/null
